services:
  postgres:
    container_name: postgres
    image: postgres:14.13-alpine3.20
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${PG_DATABASE_NAME}
      - POSTGRES_USER=${PG_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${PG_DATABASE_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nestjs_fundamentals']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
